# Generated by Django 2.2.4 on 2019-08-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='current_hints',
            field=models.CharField(default='', max_length=200),
        ),
    ]
