# Generated by Django 2.2.4 on 2019-08-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190826_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='current_hints',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
